# Generated by Django 5.2 on 2025-04-27 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200, null=True)),
                ('rappel', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('anniversaire', 'Anniversaire'), ('sortie', 'Sortie'), ('rdv_medical', 'Rendez-vous médical'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('participants', models.ManyToManyField(related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
