bases de données :
  - nom : mysitedb 
    forfait : gratuit
    nom de la base de données : monsite
    utilisateur : monsite

prestations :
  - type : web 
    forfait : gratuit
    nom : monsite
    exécution : python
    Commande de construction : './build.sh' 
    Commande de démarrage : Commande de démarrage : 'python -m gunicorn orgalove.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars :
      - clé : URL_BASE_DE_DONNEES 
        de la base de données :
          nom : mysitedb
          propriété : connectionString
      - clé : SECRET_KEY 
        generateValue : vrai 
      - clé : WEB_CONCURRENCY 
        valeur : 4 